### ISSUE TITLE
AUDIO: Recorder Poly + Reverse bug & Loop with key held bug

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#105]
using a poly keyboard or midi keyboard stops the reverse from working

switching between looping and non looping while playing the recorder with a keyboard does strange things with overdubbing the buffer - yet to single out which action causes it

**Comment by lukephills** [comment]
I've fixed it for the recorder. I was previously setting the reverse on each of the samplers when it only needs to be done once because the buffer is shared. 

There's still the same problem with the soundcloud but the fix isn't as simple. Like we discussed, I'm gonna try and get the soundcloud to reuse the same buffer, instead of passing in the track url.
