### ISSUE TITLE
AUDIO: Disconnecting power block, TriggerRelease not working

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#112]
Sound just stops instead of releasing properly if you have a power block connected to source blocks and disconnect them.

**Comment by lukephills** [comment]
I think this is related to #41 - pre effect issues.

At the point when the triggerRelease is called, the Envelopes release value is set to its default. It's almost like all the blocks are getting detached and then reattached under the hood.

**Comment by lukephills** [comment]
Yep this is exactly what is happening in `Source.ts` `Refresh()` line 114. 

Test case: 

1. Have one source and 2 effects
2. Put a breakpoint on `Source.ts` line 114 in the `Refresh()` method.
3. Disconnect one effect.

All blocks get disconnected and then the proximity gets checked and those within it get reconnected.

This is causing the connection issues that we're having with the pre effects. @edsilv is it possible to change the logic so that only the block that we are detaching gets removed from the collection instead of removing all of them in this brute force way?
