### ISSUE TITLE
UI: Device pixel ratio bug.

### ISSUE THREAD

**Issue by lukephills** [BlokDust/BlokDust#119]
Have just noticed this one. If I'm zoomed in at 50% the UI sizing is all correct however if I'm at the default zoom it looks like this. Note that the zoom doesn't effect the blocks. They are always the correct size regardless of zoom amount.

<img width="1280" alt="screenshot 2015-07-26 18 38 20" src="https://cloud.githubusercontent.com/assets/6436772/8895114/1d9bbfec-33c6-11e5-98f0-f685badd5ff0.png">

<img width="1280" alt="screenshot 2015-07-26 18 38 11" src="https://cloud.githubusercontent.com/assets/6436772/8895116/276b66ee-33c6-11e5-9ec9-247f0812be98.png">

**Comment by Whitevinyl** [comment]
Is that the browser zoom level you're changing there?
Pretty sure we can set a meta tag in the header of default.html which stops users being able to set it, strange that it defaults at 50% though - is that a retina thing on all sites or just ours?

What happens when you select "actual size" chrome's view options?

**Comment by Whitevinyl** [comment]
Is that the browser zoom level you're changing there?
Pretty sure we can set a meta tag in the header of default.html which stops users being able to set it, strange that it defaults at 50% though - is that a retina thing on all sites or just ours?
What happens when you select "actual size" chrome's view options? 

www.whitevinyldesign.com 


     On Sunday, 26 July 2015, 18:44, Luke Phillips <notifications@github.com> wrote:
   

 Assigned #119 to @Whitevinyl.—

**Comment by lukephills** [comment]
This is actual size: 
<img width="1279" alt="screenshot 2015-07-26 18 55 37" src="https://cloud.githubusercontent.com/assets/6436772/8895165/f95af984-33c7-11e5-819b-5b33b780045b.png">

It doesn't default to 50%. I was on 50% for a while without realising because it was the only way I could get the share link. See https://github.com/BlokDust/BlokDust/issues/108

Since last week something has changed and everything except blocks have gone half the size.

**Comment by lukephills** [comment]
A week ago if I changed the browser zoom nothing changed

**Comment by Whitevinyl** [comment]
Ah ok I've messed something up in moving it then - have moved the pixel ratio stuff to App.Metrics (AppMetrics.ts)
trying to make all of the metrics stuff app universal and in one place, but I probably broke something in moving it. will take a look and see if i can spot something

**Comment by Whitevinyl** [comment]
In AppMetrics.ts - line 40

try changing to:
App.Unit = (width/screenDivision)*ratio;

see if that works?

**Comment by lukephills** [comment]
Yep thats fixed it. Nice one!
