### ISSUE TITLE
Splash.ts - inherit from DisplayObject

### ISSUE THREAD

**Issue by edsilv** [BlokDust/BlokDust#133]
Code duplication not necessary.

**Comment by edsilv** [comment]
You could make the splash screen a display object and add to BlockSketch's display list. BlocksSketch is like Flash's 'Stage' - having another sketch for the splash screen would be like having two stages.

Perhaps we should rename BlocksSketch to Stage...

**Comment by Whitevinyl** [comment]
I've already fixed this, same for AnimationsLayer. will push in a bit.
However BlocksSketch isn't like the stage, because we don't create it until after serialisation, which means drawing can't happen before if DisplayObjects are dependent on it.

This means BlocksSketch is a scene, and should probably be renamed to something like MainScene. Splash is also a Scene and is created without having to wait for BlocksSketch. Could be renamed SplashScene.

**Comment by edsilv** [comment]
Cool. Are they inheriting from DisplayObject?

Yep, will rename to MainScene.

**Comment by edsilv** [comment]
I suppose App.ts has become the 'Stage' as it is the parent of all drawable elements.

**Comment by Whitevinyl** [comment]
Yeah both DisplayObjects now. Maybe DisplayObject could default to always use App's "Ctx" context unless another is specified ( if we want to draw to an offscreen canvas in future etc ).

**Comment by edsilv** [comment]
I've updated DisplayObject so that you have to pass an ISketchContext to it. This just means that the sketch parameter needs to have a minimum of a `Ctx: CanvasRenderingContext2d` property to draw to. MainScene.ts and App.ts both have this.

I think DisplayObject should remain generic, having no knowledge of the specific application it's being used in.
