### ISSUE TITLE
POWER: disposing power block while connected doesn't trigger release

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#157]

**Comment by lukephills** [comment]
Hi @edsilv,

Any chance you could have a look at this one? 

When you dispose a power block thats connected to a Source. `Stop()` gets called on the power block and I'd like to refresh connections here but the power is still connected to the Source because `RemoveItemFromArrayOperation` happens asynchronously. Any chance we can await `RemoveItemFromArrayOperation` to finish before calling `Stop()`; 

See the console.log's in 'DeleteBlockOperation.ts', lines 26 - 28 to see what I mean.
