### ISSUE TITLE
ENVELOPE: scheduled stop with long release

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#251]
Bit different to the other issue. 
When playing samples with a long envelope release in monophonic, playing one note, and releasing it, then playing a second note before the first release ended, will cause the new note to suddenly stop playing at the point when the first release would have ended if it was left to ring out.

**Comment by lukephills** [comment]
1. click and hold to triggerAttack
2. clickUp to triggerRelease
3. click and hold again (before release has ended)

No.3 - envelope ramps the volume back up but the player can't play the sample because the sample is already playing. It then suddenly stops because no.2 has scheduled it to stop after the release time.

I'm not sure how to proceed with this one without breaking other things.

**Comment by lukephills** [comment]
Fixed in Tone.SimpleEnvelope & Tone.SimplePlayer refactor.
