### ISSUE TITLE
COMP KEYS: Change key layout

### ISSUE THREAD

**Issue by Whitevinyl** [BlokDust/BlokDust#273]
I've always found our keyboard layout a little unintuitive, but didn't put much thought into it as we were working on other stuff. But The other day I went back and tried that Tune.js demo:

http://abbernie.github.io/tune/

And it made me realise how much I prefer this layout, it's more conventional to have the higher octave keys above rather than below, and the way we currently have it means T is middle-C/C4, which feels a bit strange. Normally when playing on the lower octave I immediately go to Q as that feels like it should be the start of an octave layout.
How do we feel about changing to a layout like above, but extend it to use all the keys we're currently using? So Z will become C4, or possibly C3, but either way Z & Q will both be C notes.

I'm just filling out the final pages on the Guide, I think it'd be nice to mention the key layout on the Computer Keyboard page.

**Comment by lukephills** [comment]
I think the reason the T key became middle C is because I wanted to fit in as many notes as possible  whilst making sure the Z key was a C note. I also liked that you could get a 5th lower than a C in the bass notes (the Q key). Since then we added the transpose setting which made that redundant so yeah probably would be better putting C on the Q key as well.

**Comment by lukephills** [comment]
Yep, it does make more sense having the lower notes lower on the keyboard and starting C4 on the Q is nice because you can get up to G5 on the ] key
