### ISSUE TITLE
Up and down key octave shift

### ISSUE THREAD

**Issue by lukephills** [BlokDust/BlokDust#94]
Up and down key octave shift doesn't work properly with multiple sources connected one keyboard and pitch effects connected.

**Comment by lukephills** [comment]
Fixed OctaveShift method.

When using up and down arrows and the params panel is open it would be nice to see the slider update accordingly.

**Comment by Whitevinyl** [comment]
Have made the options panel update, but the octaveshift method still has bugs - if 2 sources are attached it jumps 2 octaves at a time, 3 sources = 3 octaves etc.

Will talk about this tomorrow, I think we should do a bit of refactoring with a controller class, so that controllers only pass messages to sources and don't need to get/convert frequencies or do source specific code
